FROM node:24-alpine3.20
WORKDIR /app

# Copy package.json and package-lock.json
COPY Frontend/lazycook/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY Frontend/lazycook/ .

RUN npm run build

ENV PORT=8000

#EXPOSE 8000

CMD ["npm", "start"]